import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "ImageUpload",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-small.svg", // Ou "/favicon.ico" se preferir
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Remova a tag <link> manual */}
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
