import { Geist, Geist_Mono } from "next/font/google";
import Upload from "./upload/page";
import "./globals.css";

export const metadata = {
  title: "Upload Image",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
