import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "ImageUpload",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-small.svg", // Ou "/favicon.ico" se preferir
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo-small.svg" type="image/svg+xml" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
